//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_Tischreservierung
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservierung
    {
        public int Reservierungsnummer { get; set; }
        public string Datum { get; set; }
        public string Reservierungsdatum { get; set; }
        public Nullable<int> Kundennummer { get; set; }
        public Nullable<int> Tischnummer { get; set; }
    
        public virtual Kunde Kunde { get; set; }
        public virtual Tisch Tisch { get; set; }
    }
}
